export const UI_TEXT = {
  addLibrary: "Add library folder",
  collapse: "Collapse",
  expand: "Expand",
  sectionFolders: "Folders",
  sectionAlbums: "Albums",
  sectionPeople: "People",
  sectionSettings: "Settings",
  noFolder: "Select a folder to view media",
  noPhotos: "No images or videos found in selected folder",
  analyzePhotos: "Analyze photos",
  analysisPanelTitle: "Local AI analysis",
  faceDetectionPanelTitle: "Local face detection",
  analysisIdle: "Select a folder and run analysis.",
  analysisRunning: "Analysis in progress...",
  analysisDone: "Analysis finished.",
  analysisFailed: "Analysis unavailable. Ensure Ollama is running locally.",
  analysisTimeLeftLabel: "Time left",
  faceDetectionIdle: "Select a folder and run face detection.",
  faceDetectionRunning: "Face detection in progress...",
  faceDetectionDone: "Face detection finished.",
  faceDetectionFailed: "Face detection unavailable. Ensure RetinaFace API is running locally.",
  faceDetectionServiceHealthy: "Face detection service is ready.",
  faceDetectionServiceUnavailable: "Face detection service is unavailable.",
  faceDetectionServiceRestarting: "Face detection service is restarting — retrying failed images automatically…",
  faceCountLabel: "Faces",
  gridView: "Grid view",
  listView: "List view",
  filterMenuOpen: "Open filters",
  filterMenuClose: "Close filters",
  filterMenuTitle: "Quick filters",
  filterPeople: "People",
  filterUserRating: "Rating",
  filterAiRating: "AI Rating",
  filterCategories: "Categories",
  filterDocuments: "Documents",
  filterMultiChoice: "Mutli-choice:",
  filterClearAll: "Clear all filters",
  filterSummaryPrefix: "Filtered",
  noPhotosForFilters: "No photos match current filters",
  albumActions: "Album actions",
  faceDetection: "Face detection",
  photoAIAnalysis: "Image AI analysis",
  imageEditSuggestions: "Image edit suggestions",
  scanForFileChanges: "Scan for file changes",
  folderAiAnalysisSummary: "Folder AI analysis summary",
  folderAiSummaryTitle: "Folder AI analysis summary",
  folderAiSummaryBack: "Back to photos",
  folderAiSummaryColumnFolder: "Folder",
  folderAiSummaryColumnImages: "Images",
  folderAiSummaryColumnFace: "Face detection",
  folderAiSummaryColumnPhoto: "AI Image analysis",
  folderAiSummaryColumnSemantic: "AI search index",
  folderAiSummaryThisFolder: "Total with sub-folders",
  folderAiSummaryThisFolderDirectOnly: "This folder without sub-folders",
  folderAiSummarySubfolders: "Sub-folders",
  folderAiSummaryLoading: "Loading summary…",
  folderAiSummaryRefresh: "Refresh",
  folderAiSummaryNote: "Based on last folders scan and AI analysis timestamps in database",
  folderAiSummaryError: "Could not load folder summary.",
  folderAiSummaryStatusEmpty: "No images",
  folderAiSummaryStatusDone: "Done",
  folderAiSummaryStatusNotDone: "Not done",
  /** Hover / title for partial pipeline cells in Folder AI analysis summary. */
  folderAiSummaryStatusPartial: "Incomplete",
  folderAiSummaryStatusFailed: "Failed",
  /** Native tooltip on failed-count lines in Folder AI analysis summary. */
  folderAiSummaryStatusFailedCorrupt: "Failed: typically corrupt file",
  folderAiPipelineStripLabel: "AI pipeline status for this folder (direct images only)",
  folderAiPipelineStripImagesOnlyHint: "AI status (images only)",
  folderAiPipelineStripUnavailable: "AI status unavailable",
  metadataScanFollowUpTitle: "Catalog update detected",
  metadataScanFollowUpDismiss: "Dismiss",
  metadataScanFollowUpPhoto: "Photo AI (missing)",
  metadataScanFollowUpFace: "Face detection (missing)",
  metadataScanFollowUpSemantic: "AI search index (missing)",
  cancelFaceDetection: "Cancel face detection",
  cancelPhotoAnalysis: "Cancel image AI analysis",
  onlyIfMissing: "Only if missing",
  allPhotos: "All photos",
  semanticPanelTitle: "AI image search",
  semanticSearchPlaceholder: "e.g. Bald man with a woman on a beach...",
  semanticSearch: "Search",
  semanticSearchSignalModeLabel: "Matching method",
  semanticSearchSignalHybrid: "VLM + Description",
  semanticSearchSignalVlmOnly: "VLM only",
  semanticSearchSignalDescriptionOnly: "Description only",
  semanticClear: "Clear results",
  semanticSearchNoResultsTitle: "Nothing found",
  semanticSearchNoResultsAboveThreshold:
    "All search results are below similarity threasholds defined in Settings → AI image search",
  semanticIndexFolder: "Index selected folder",
  semanticCancelIndex: "Cancel indexing",
  semanticOpen: "Open AI image search",
  semanticClose: "Close AI image search",
  semanticIndexTitle: "Index images for AI search",
  semanticIndexPanelTitle: "AI search indexing",
  semanticIndexLoadingVisionModel: "Loading vision embedding model…",
  cancelSemanticIndex: "Cancel AI search indexing",
  // TEMPORARY: description embedding backfill — remove after migration
  descEmbedBackfillTitle: "AI description embedding",
  descEmbedBackfillPanelTitle: "AI description embedding",
  cancelDescEmbedBackfill: "Cancel description embedding",
  cancelScan: "Cancel scan",
  metadataScanIdle: "Metadata scan idle.",
  metadataScanRunning: "Metadata scan in progress...",
  metadataScanDone: "Metadata scan completed.",
  metadataScanFailed: "Metadata scan failed.",
  /** Shown above the progress bar while recording file identity before reading metadata. */
  metadataScanPreparing: "Checking files on disk",
  /** Second phase: read sidecar/embedded metadata and upsert catalog rows. */
  metadataScanScanning: "Reading metadata and updating catalog",
  /** Card heading when the scan is idle, completed, or the phase is not shown separately. */
  metadataScanCardTitle: "Media metadata scan",
  /** Card heading during the file-identity / observe phase (folder name is appended by the UI). */
  metadataPreparingCardTitle: "Media metadata scan - Indexing file identity",
  /** Card heading while processing each file’s metadata against the catalog. */
  metadataScanScanningCardTitle: "Media metadata scan - updating catalog",
  loadingFolder: "Loading folder photos...",
  progressPanelTitle: "Background operations",
  progressPathAnalysisTitle: "Path metadata (LLM)",
  pathAnalysisMenuTitle: "Extract path metadata (LLM)",
  progressPanelCollapse: "Collapse background operations panel",
  progressPanelExpand: "Expand background operations panel",
  preparingFiles: "Preparing file list…",
  analysisLoadingModel: "Loading AI model - it may take 1-2min",
  faceClusteringPanelTitle: "Grouping untagged faces",
  faceClusteringPhaseLoading: "Loading embeddings…",
  faceClusteringPhaseClustering: "Finding similar faces… Face pairs:",
  faceClusteringPhasePersisting: "Saving face groups…",
  faceClusteringCancel: "Cancel grouping",
  faceClusteringClose: "Close grouping status",
  similarUntaggedCountsPanelTitle: "People tab: similar face counts",
  similarUntaggedCountsCancel: "Cancel similar face counts",
  similarUntaggedCountsClose: "Close similar face counts status",
  revealInFileExplorer: "Show in File Explorer",
  copyFilePath: "Copy file path",
  videoAiUnavailable: "AI analysis is not available for videos yet",
  gpsLocationDetectionTitle: "Detect Country / City from GPS coordinates",
  gpsLocationDetectionDescription: `When enabled, photos with GPS coordinates are reverse-geocoded during metadata scan to fill in Country, State/Province, and City. This data is used in search filters, folder/album views, and smart albums.

First-time setup downloads ~2 GB of GeoNames geographic data (cached locally for future use).`,
  gpsLocationDetectionConfirmTitle: "Download location data?",
  gpsLocationDetectionConfirmMessage: "This will download approximately 2 GB of geographic data from GeoNames. The download happens in the background and data is cached locally for future use.",
  gpsLocationDetectionConfirmOk: "Download",
  gpsLocationDetectionConfirmCancel: "Cancel",
  geocoderInitPanelTitle: "GPS location database",
  geocoderInitDownloading: "Downloading GeoNames data (~2 GB)…",
  geocoderInitParsing: "Building location index…",
  geocoderInitReady: "Location database ready.",
  geocoderInitError: "Location database initialization failed.",
} as const;
