export const UI_TEXT = {
  addLibrary: "Add library folder",
  collapse: "Collapse",
  expand: "Expand",
  sectionFolders: "Folders",
  sectionAlbums: "Albums",
  sectionPeople: "People",
  sectionSettings: "Settings",
  noFolder: "Select a folder to view media",
  noPhotos: "No images or videos found in selected folder",
  analyzePhotos: "Analyze images",
  analysisPanelTitle: "Local AI analysis",
  faceDetectionPanelTitle: "Local face detection",
  analysisIdle: "Select a folder and run analysis.",
  analysisRunning: "Analysis in progress...",
  analysisDone: "Analysis finished.",
  analysisFailed: "Analysis unavailable. Ensure Ollama is running locally.",
  analysisTimeLeftLabel: "Time left",
  faceDetectionIdle: "Select a folder and run face detection.",
  faceDetectionRunning: "Face detection in progress...",
  faceDetectionDone: "Face detection finished.",
  faceDetectionFailed: "Face detection unavailable. Ensure RetinaFace API is running locally.",
  faceDetectionServiceHealthy: "Face detection service is ready.",
  faceDetectionServiceUnavailable: "Face detection service is unavailable.",
  faceDetectionServiceRestarting: "Face detection service is restarting — retrying failed images automatically…",
  faceCountLabel: "Faces",
  gridView: "Grid view",
  listView: "List view",
  filterMenuOpen: "Open filters",
  filterMenuClose: "Close filters",
  filterMenuTitle: "Quick filters",
  filterPeople: "People",
  filterUserRating: "Rating",
  filterAiRating: "AI Rating",
  filterCategories: "Categories",
  filterDocuments: "Documents",
  filterMultiChoice: "Mutli-choice:",
  filterClearAll: "Clear all filters",
  filterSummaryPrefix: "Filtered",
  noPhotosForFilters: "No images match current filters",
  albumActions: "Album actions",
  faceDetection: "Face detection",
  photoAIAnalysis: "Image AI analysis",
  imageEditSuggestions: "Image edit suggestions",
  scanForFileChanges: "Scan for file changes",
  folderAiAnalysisSummary: "Folder AI analysis summary",
  folderAiSummaryTitle: "Folder AI analysis summary",
  folderAiSummaryFolderTitle: "Folder analysis summary",
  folderAiSummaryTreeTitle: "Folder tree analysis summary",
  folderAiSummaryTabSummary: "Summary",
  folderAiSummaryTabFaceDetection: "Face detection",
  folderAiSummaryTabAiPipelines: "Subfolders",
  folderAiSummaryTabGeoLocation: "Geo-location",
  folderAiSummaryActionShort: "Analysis",
  folderAiSummaryActionOpen: "Open folder analysis summary",
  folderAiSummaryTreeActionCta: "Folder tree analysis summary",
  folderAiSummaryBack: "Back to images",
  folderAiSummaryColumnFolder: "Folder",
  folderAiSummaryColumnImages: "Images",
  folderAiSummaryColumnVideos: "Videos",
  folderAiSummaryColumnImagesGps: "Images with GPS",
  folderAiSummaryColumnVideosGps: "Videos with GPS",
  folderAiSummaryColumnFilesGps: "Files with GPS",
  folderAiSummaryColumnLocationDetails: "GPS Location extracted",
  folderAiSummaryColumnPathLlmLocationDetails: "Location from file path by LLM",
  folderAiSummaryColumnFace: "Face detection",
  folderAiSummaryColumnPhoto: "AI Image analysis",
  folderAiSummaryColumnSemantic: "AI search index",
  folderAiSummaryColumnRotation: "Wrongly rotated images",
  /** Subfolders table header only (dashboard card still uses folderAiSummaryColumnRotation) */
  folderAiSummaryColumnRotationAnalysis: "Rotation analysis",
  /** Subfolder table rotation column detail line: shown as "{prefix}: N" when N > 0 */
  folderAiSummaryWronglyRotatedCountPrefix: "Wrongly rotated",
  folderAiSummaryRotationReviewOpen: "View wrongly rotated images",
  folderAiSummaryFolderScanTitle: "Folder scan",
  folderAiSummaryFolderTreeScanTitle: "Folder tree scan",
  folderAiSummaryFolderScanHelp:
    "Shows how fresh the folder scan data is. Oldest scan is the oldest completed scan timestamp in this folder tree. Last data change is the latest time file metadata was extracted into the catalog. Not scanned counts direct sub-folders whose tree still has missing scan data.",
  folderAiSummaryDashboardImagesSection: "Images:",
  folderAiSummaryFileScanMetadataSection: "File scan and metadata",
  folderAiSummaryDashboardPrototypeVariants: "Card style variants",
  folderAiSummaryGeoLocation: "Geo-location",
  folderAiSummaryGpsWith: "With GPS",
  folderAiSummaryGpsWithout: "Without GPS",
  folderAiSummaryLocationDetailsDone: "Location details extracted",
  folderAiSummaryThisFolder: "Total with sub-folders",
  folderAiSummaryThisFolderDirectOnly: "This folder without sub-folders",
  folderAiSummarySubfolders: "Sub-folders",
  folderFaceTableColumnFaceDetectionLine1: "Face detection",
  folderFaceTableColumnFaceDetectionLine2: "status",
  folderFaceTableColumnFacesTaggedLine1: "Faces",
  folderFaceTableColumnFacesTaggedLine2: "Tagged",
  folderFaceTableColumnSuggestedMatches: "Suggested matches",
  folderFaceTableColumnPeoplePerImage: "People per image",
  /** People-per-image cell: prefix before person icon for the four-or-more bucket */
  folderFaceTablePeoplePerImageFourPlusPrefix: "4+",
  folderFaceTableTaggedHelp:
    "Tagged counts faces with a confirmed person-tag (applied directly or via accepted suggestion).",
  folderFaceTableComputing: "Computing face statistics…",
  folderAiSummaryLoading: "Loading summary…",
  folderAiSummaryRefresh: "Refresh",
  folderAiSummaryNote: "Based on last folders scan and AI analysis timestamps in database",
  folderAiSummaryError: "Could not load folder summary.",
  folderAiSummaryStatusEmpty: "No images",
  folderAiSummaryStatusDone: "Done",
  folderAiSummaryStatusNotDone: "Not done",
  /** Hover / title for partial pipeline cells in Folder AI analysis summary. */
  folderAiSummaryStatusPartial: "Incomplete",
  folderAiSummaryStatusFailed: "Failed",
  /** Native tooltip on failed-count lines in Folder AI analysis summary. */
  folderAiSummaryStatusFailedCorrupt: "Failed: typically corrupt file",
  folderAiSummaryFailedListOpen: "Open failed files list",
  folderAiSummaryFailedListTitle: "Folder AI failed files",
  folderAiSummaryFailedListBack: "Back to summary",
  folderAiSummaryFailedListEmpty: "No failed files found for this selection.",
  folderAiSummaryFailedListError: "Could not load failed files list.",
  folderAiPipelineStripLabel: "AI pipeline status for this folder (direct images only)",
  folderAiPipelineStripImagesOnlyHint: "AI status (images only)",
  folderAiPipelineStripUnavailable: "AI status unavailable",
  metadataScanFollowUpPhoto: "AI image analysis",
  metadataScanFollowUpFace: "Face detection",
  metadataScanFollowUpSemantic: "AI search index",
  metadataScanFollowUpFilePhrase: "file(s) across",
  metadataScanFollowUpFolderPhrase: "folder(s)",
  metadataScanFollowUpLineTail: "may still need AI analysis. You can run:",
  cancelFaceDetection: "Cancel face detection",
  cancelPhotoAnalysis: "Cancel image AI analysis",
  onlyIfMissing: "Only if missing",
  allPhotos: "All images",
  semanticPanelTitle: "AI image search",
  semanticSearchPlaceholder: "e.g. Lady in white dress near piano",
  semanticSearch: "Search",
  semanticSearchSignalModeLabel: "Matching method",
  semanticSearchSignalHybrid: "VLM + Description",
  semanticSearchSignalVlmOnly: "VLM only",
  semanticSearchSignalDescriptionOnly: "Description only",
  semanticClear: "Clear results",
  semanticSearchNoResultsTitle: "Nothing found",
  semanticSearchNoResultsAboveThreshold:
    "All search results are below similarity threasholds defined in Settings → AI image search",
  semanticIndexFolder: "Index selected folder",
  semanticCancelIndex: "Cancel indexing",
  semanticOpen: "Open AI image search",
  semanticClose: "Close AI image search",
  /** List view: cosine vs vision embedding (VLM) vs query. */
  semanticListVlmScoreLabel: "Visual similarity score (VLM):",
  /** List view: cosine vs AI caption text embedding (not a chat LLM). */
  semanticListDescriptionScoreLabel: "AI description match score (LLM):",
  semanticIndexTitle: "Index images for AI search",
  semanticIndexPanelTitle: "AI search indexing",
  semanticIndexLoadingVisionModel: "Loading vision embedding model…",
  cancelSemanticIndex: "Cancel AI search indexing",
  // TEMPORARY: description embedding backfill — remove after migration
  descEmbedBackfillTitle: "AI description embedding",
  descEmbedBackfillPanelTitle: "AI description embedding",
  cancelDescEmbedBackfill: "Cancel description embedding",
  cancelScan: "Cancel scan",
  metadataScanIdle: "Metadata scan idle.",
  metadataScanRunning: "Metadata scan in progress...",
  metadataScanDone: "Metadata scan completed.",
  metadataScanFailed: "Metadata scan failed.",
  /** Shown above the progress bar while recording file identity before reading metadata. */
  metadataScanPreparing: "Checking files on disk",
  /** Second phase: read sidecar/embedded metadata and upsert database rows. */
  metadataScanScanning: "Reading metadata and updating database",
  /** Optional phase: reverse-geocode GPS coordinates into country/city fields. */
  metadataScanGeocoding: "Updating location data from GPS",
  /** Card heading when the scan is idle, completed, or the phase is not shown separately. */
  metadataScanCardTitle: "Media metadata scan",
  /** Card heading during the file-identity / observe phase (folder name is appended by the UI). */
  metadataPreparingCardTitle: "Media metadata scan - Indexing file identity",
  /** Card heading while processing each file’s metadata against the database. */
  metadataScanScanningCardTitle: "Media metadata scan - updating database",
  /** Card heading while reverse-geocoding GPS metadata. */
  metadataScanGeocodingCardTitle: "Media metadata scan - updating locations",
  loadingFolder: "Loading folder images...",
  progressPanelTitle: "Background operations",
  progressPathAnalysisTitle: "Path metadata (LLM)",
  pathAnalysisMenuTitle: "Extract path metadata (LLM)",
  progressPanelCollapse: "Collapse background operations panel",
  progressPanelExpand: "Expand background operations panel",
  preparingFiles: "Preparing file list…",
  analysisLoadingModel: "Loading AI model - it may take 1-2min",
  faceClusteringPanelTitle: "Grouping untagged faces",
  faceClusteringPhaseLoading: "Loading embeddings…",
  faceClusteringPhaseClustering: "Finding similar faces… Face pairs:",
  faceClusteringPhasePersisting: "Saving face groups…",
  faceClusteringPhaseRefreshingSuggestions: "Refreshing people suggestions…",
  faceClusteringCancel: "Cancel grouping",
  faceClusteringClose: "Close grouping status",
  similarUntaggedCountsPanelTitle: "People tab: similar face counts",
  similarUntaggedCountsCancel: "Cancel similar face counts",
  similarUntaggedCountsClose: "Close similar face counts status",
  revealInFileExplorer: "Show in File Explorer",
  copyFilePath: "Copy file path",
  videoAiUnavailable: "AI analysis is not available for videos yet",
  gpsLocationDetectionTitle: "Detect Country / City from GPS coordinates",
  gpsLocationDetectionDescription: `When enabled, images with GPS coordinates are reverse-geocoded during metadata scan to fill in Country, State/Province, and City. This data is used in search filters, folder/album views, and smart albums.

First-time setup downloads ~2 GB of GeoNames geographic data (cached locally for future use).`,
  gpsLocationDetectionConfirmTitle: "Download location data?",
  gpsLocationDetectionConfirmMessage: "This will download approximately 2 GB of geographic data from GeoNames. The download happens in the background and data is cached locally for future use.",
  gpsLocationDetectionConfirmOk: "Download",
  gpsLocationDetectionConfirmCancel: "Cancel",
  geocoderInitPanelTitle: "GPS location database",
  geocoderInitDownloading: "Downloading GeoNames data (~2 GB)…",
  geocoderInitLoadingCache: "Loading cached GeoNames data…",
  geocoderInitParsing: "Building location index…",
  geocoderInitReady: "Location database ready.",
  geocoderInitError: "Location database initialization failed.",
  metadataManualScanResultTitle: "Scan results",
  metadataManualScanResultClose: "Close scan results",
  metadataManualScanRecursiveHint: "Including subfolders",
  metadataManualScanCancelledHint:
    "The scan was cancelled; the lists below reflect changes found before cancellation (missing files are listed only if file discovery had finished).",
  metadataManualScanGroupNew: "New files",
  metadataManualScanGroupUpdated: "Updated files",
  metadataManualScanGroupMoved: "Renamed or moved",
  metadataManualScanGroupDeleted: "Missing on disk, but kept as inactive in database",
  metadataManualScanGroupFailed: "Failed",
  metadataManualScanPathColumnPrevious: "Previous path",
  metadataManualScanPathColumnNew: "New path",
  metadataManualScanShowAll: "Show all",
  metadataManualScanShowLess: "Show first 50",
  metadataManualScanPurgeDeleted: "Remove missing files from database (faces, embeddings, tags)",
  metadataManualScanPurgeConfirm:
    "Permanently remove these missing files from the database and delete related face detections, embeddings, and tags? This cannot be undone.",
  metadataManualScanPurgeWorking: "Removing…",
} as const;
